platform :ios, '26.0'

target 'OpenFlightApp' do
  use_frameworks!
  pod 'GroundSdk'
  pod 'ArsdkEngine'
  pod 'SdkCore'
  pod 'OpenFlightCore'
  pod 'SwiftGen'
  pod 'SwiftLint'
  pod 'Reusable'
  pod 'SwiftyUserDefaults'
  pod 'KeychainAccess'
  pod 'lottie-ios'
  pod 'ArcGIS-Runtime-SDK-iOS'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '26.0'
               end
          end
   end
end
